### ISSUE TITLE
怎么使用该项目

### ISSUE THREAD

**Issue by qw-code** [jiandandaoxingfu/latex-toolbox#29]
不是专业的搞计算机的，查了半天也不知道怎么运行这个项目

**Comment by jiandandaoxingfu** [comment]
@19303024671  如果只是用的话, 直接打开github pages就行了, 就是个在线工具. 地址: https://jiandandaoxingfu.github.io/maple-latex/
文档地址:
https://jiandandaoxingfu.github.io/myblog/post/maple-latex/
