### ISSUE TITLE
is there a document？

### ISSUE THREAD

**Issue by Runfa-Zhang** [jiandandaoxingfu/latex-toolbox#3]
is there a document？

**Comment by jiandandaoxingfu** [comment]
文档参见[Maple-Latex](https://jiandandaoxingfu.github.io/myblog/post/maple-latex/)

**Comment by jiandandaoxingfu** [comment]
> is there a document？

文档参见[Maple-Latex](https://jiandandaoxingfu.github.io/myblog/post/maple-latex/)
