### ISSUE TITLE
对于软件改进的一些建议

### ISSUE THREAD

**Issue by zhou-tian-xing** [jiandandaoxingfu/latex-toolbox#30]
在我使用Maple-Latex时（如下图），翻译结果许多地方有问题，我认为还可以再改进
![结果](https://user-images.githubusercontent.com/57858579/233760397-fb04af8c-c9e7-49b3-b19c-caedeb3b7b0d.png)
###### 3. 公式中的大型运算符格式均不对，下图中为正确结果的求和符号、积分符号、极限符号
![求和](https://user-images.githubusercontent.com/57858579/233760730-b80a65e3-080d-4936-a465-17b0603738a8.png)

![不定积分](https://user-images.githubusercontent.com/57858579/233760852-48d53584-98f2-462c-a5de-a24cc83e7c19.png)

![定积分](https://user-images.githubusercontent.com/57858579/233760986-0de94956-34b1-423a-a970-550aae3b7f93.png)

![定积分2](https://user-images.githubusercontent.com/57858579/233761251-ac7315a7-bf96-4483-9250-89c8a86a34a3.png)

![极限](https://user-images.githubusercontent.com/57858579/233761086-b291ccd4-c9de-4358-b9cc-9580c1dffc59.png)

###### 5. 颜色环境未移除，结果内可见 color Blue 等

附：
第一幅图中的latex：
`
\frac{\frac{{\color{Blue} \int_{0}^{+\infty } e^{-s} s^{5} ds }}{2} 
+\frac{{\color{Brown} \int_{-\infty }^{+\infty } e^{-\frac{t^{2}}{2}}dt } }
{{\color{Gray}  \int_{0}^{+\infty } \sin t^{2} dt}} 
\left (  \frac{{\color{Green} \sum_{n=0}^{\infty } \frac{\left ( -1 \right )^{n}}{2n+1}  }}
{{\color{Orange}\int_{0}^{+\infty }\frac{\sin x}{x} dx  } }
+\frac{{\color{Purple} \sum_{n=1}^{\infty }\arctan \frac{2}{n^{2} }   }}
{{\color{Red} \lim_{t \to 0} \int_{-2020}^{2020}\frac{t\cos x}{x^{2}+t^{2}}dx}  }\right )}
{{\color{Violet}\lim_{n \to \infty}\left \{ \left [ \left ( \int_{0}^{1}\frac{x^{n-1} }{1+x} dx  \right ) n-\frac{1}{2}  \right ]  \frac{n}{2} \right \}   }  }=
`
翻译结果：
`
(( ( color Blue int0^(+infty) exp(-s) s^5 ds ) )/ 2 
+( ( color Brown int[-infty]^(+infty) exp(-(t^2)/ 2 )dt ) )/
 ( ( color Gray int0^(+infty) sint^2 dt ) ) 
left ( ( ( color Green sum[n=0]^infty (left ( -1 right )^n)/ ( 2n+1 ) ) )/
 ( ( color Orange int0^(+infty) ( sinx)/ x dx ) ) 
+( ( color Purple sum[n=1]^infty arctan2/ ( n^2 ) ) )/
 ( ( color Red lim[t to 0] int[-2020]^2020 (t cosx)/ ( x^2+t^2 ) dx ) ) right ))/
 ( ( color Violet lim[n to infty]left ( left ( left ( int0^1 (x^(n-1) )/ ( 1+x ) dx right ) n-1/ 2 right ) n/ 2 right ) ) ) =
`

**Comment by jiandandaoxingfu** [comment]
@zhou-tian-xing 
好的, 谢谢你. 因为主要是我自己在用, 平时主要处理一些微分多项式, 所以很多其它情况都没有做处理.
你提的这几点我后续尽可能添加上去.

**Comment by jiandandaoxingfu** [comment]
@zhou-tian-xing 
另外, 你这个latex可能是自己写的, 目前的功能只处理 mathpix snipping tool 识别生成的latex. 
因为每个人书写习惯可能都不太一样, 情况比较复杂. 这个公式识别软件的话, 生成的 latex 基本比较统一, 处理起来方便一点.

例如, 你给的公式利用 mathpix snipping tool 识别生成的 latex 为
```latex
\frac{\int_0^{+\infty} e^{-s} s^5 d s}{2}+\frac{\int_{-\infty}^{+\infty} e^{-\frac{t^2}{2}} d t}{\int_0^{+\infty} \sin t^2 d t}\left(\frac{\sum_{n=0}^{\infty} \frac{(-1)^n}{2 n+1}}{\int_0^{+\infty} \frac{\sin x}{x} d x}+\frac{\sum_{n=1}^{\infty} \arctan \frac{2}{n^2}}{\lim _{t \rightarrow 0} \int_{-2020}^{2020} \frac{t \cos x}{x^2+t^2} d x}\right)
```

**Comment by jiandandaoxingfu** [comment]
@zhou-tian-xing 
已经支持积分转换, 求和与极限暂时不能添加, 这两个命令不太好判断作用对象(像积分可以根据 `d x` 来判断).

**Comment by jiandandaoxingfu** [comment]
对于极限, 求和等函数, 关键问题在于如何匹配作用对象. 例如: 对于 `sin t^2 + ...` 中 `t^2` 的匹配, 当然这个比较简单. 对于多层括号嵌套, 分式等作用对象, 比较麻烦. 因为此类命令没有结束标识.
